/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve User */
        patch: operations["approve_user_api_v1_admin_users__user_id__approve_patch"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspend User */
        patch: operations["suspend_user_api_v1_admin_users__user_id__suspend_patch"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set User Role */
        patch: operations["set_user_role_api_v1_admin_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_v1_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip */
        patch: operations["update_trip_api_v1_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/gear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Trip Gear */
        post: operations["add_trip_gear_api_v1_trips__trip_id__gear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/gear/copy-from/{source_trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy Trip Gear */
        post: operations["copy_trip_gear_api_v1_trips__trip_id__gear_copy_from__source_trip_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/gear/{trip_gear_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Trip Gear
         * @description Remove the item from this trip; it stays in the closet.
         */
        delete: operations["remove_trip_gear_api_v1_trips__trip_id__gear__trip_gear_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip Gear */
        patch: operations["update_trip_gear_api_v1_trips__trip_id__gear__trip_gear_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Note */
        post: operations["add_note_api_v1_trips__trip_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_v1_trips__trip_id__notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note */
        patch: operations["update_note_api_v1_trips__trip_id__notes__note_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/checklist/{item_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Checklist Item */
        patch: operations["update_checklist_item_api_v1_trips__trip_id__checklist__item_key__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/food-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Food Plan */
        patch: operations["update_food_plan_api_v1_trips__trip_id__food_plan_patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/food-plan/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Food Item */
        post: operations["add_food_item_api_v1_trips__trip_id__food_plan_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/food-plan/items/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Food Item */
        delete: operations["delete_food_item_api_v1_trips__trip_id__food_plan_items__food_id__delete"];
        options?: never;
        head?: never;
        /** Update Food Item */
        patch: operations["update_food_item_api_v1_trips__trip_id__food_plan_items__food_id__patch"];
        trace?: never;
    };
    "/api/v1/gear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gear Items */
        get: operations["list_gear_items_api_v1_gear_get"];
        put?: never;
        /** Create Gear Item */
        post: operations["create_gear_item_api_v1_gear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gear Item */
        get: operations["get_gear_item_api_v1_gear__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Gear Item
         * @description Archive the item: it leaves the closet list but stays on trips that already pack it.
         */
        delete: operations["archive_gear_item_api_v1_gear__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Gear Item */
        patch: operations["update_gear_item_api_v1_gear__item_id__patch"];
        trace?: never;
    };
    "/api/v1/gear/{item_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Gear Item */
        post: operations["restore_gear_item_api_v1_gear__item_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChecklistItemKey
         * @enum {string}
         */
        ChecklistItemKey: "permit" | "water_sources" | "resupply_points" | "shuttle_scheduled" | "weather_checked" | "cell_coverage" | "offline_map" | "fire_restrictions" | "route_shared";
        /** ChecklistItemRead */
        ChecklistItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            item: components["schemas"]["ChecklistItemKey"];
            status: components["schemas"]["ChecklistStatus"];
            /** Details */
            details: string | null;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChecklistItemUpdate */
        ChecklistItemUpdate: {
            status?: components["schemas"]["ChecklistStatus"];
            /** Details */
            details?: string | null;
        };
        /**
         * ChecklistStatus
         * @enum {string}
         */
        ChecklistStatus: "todo" | "done" | "not_applicable";
        /** FoodPlannerRead */
        FoodPlannerRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Target Kcal Per Day */
            target_kcal_per_day: number;
            /** Target Food G Per Day */
            target_food_g_per_day: number;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Food */
            food: components["schemas"]["TripFoodRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FoodPlannerUpdate */
        FoodPlannerUpdate: {
            /** Target Kcal Per Day */
            target_kcal_per_day?: number;
            /** Target Food G Per Day */
            target_food_g_per_day?: number;
        };
        /** GearItemCreate */
        GearItemCreate: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Weight G
             * @default 0
             */
            weight_g: number;
            /** @default base */
            kind: components["schemas"]["GearKind"];
            /** Notes */
            notes?: string | null;
        };
        /** GearItemRead */
        GearItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Weight G */
            weight_g: number;
            kind: components["schemas"]["GearKind"];
            /** Notes */
            notes: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GearItemUpdate */
        GearItemUpdate: {
            /** Name */
            name?: string;
            /** Category */
            category?: string;
            /** Weight G */
            weight_g?: number;
            kind?: components["schemas"]["GearKind"];
            /** Notes */
            notes?: string | null;
        };
        /**
         * GearKind
         * @enum {string}
         */
        GearKind: "base" | "worn" | "consumable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Meal
         * @enum {string}
         */
        Meal: "breakfast" | "lunch" | "dinner" | "snack";
        /** SetRoleRequest */
        SetRoleRequest: {
            role: components["schemas"]["UserRole"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TripCreate */
        TripCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Area */
            area?: string | null;
            /** @default loop */
            trip_type: components["schemas"]["TripType"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Start Trailhead */
            start_trailhead?: string | null;
            /** End Trailhead */
            end_trailhead?: string | null;
            /** Total Distance M */
            total_distance_m?: number | null;
            /** Elevation Gain M */
            elevation_gain_m?: number | null;
            /**
             * Water Carry L
             * @default 0
             */
            water_carry_l: number;
            /** Map Link */
            map_link?: string | null;
            /** Emergency Contact */
            emergency_contact?: string | null;
        };
        /** TripFoodCreate */
        TripFoodCreate: {
            /** Day */
            day: number;
            /** Name */
            name: string;
            /** @default breakfast */
            meal_type: components["schemas"]["Meal"];
            /**
             * Servings
             * @default 1
             */
            servings: number;
            /** Weight G */
            weight_g: number;
            /** Kcal */
            kcal: number;
        };
        /** TripFoodRead */
        TripFoodRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Day */
            day: number;
            /** Name */
            name: string;
            meal_type: components["schemas"]["Meal"];
            /** Servings */
            servings: number;
            /** Weight G */
            weight_g: number;
            /** Kcal */
            kcal: number;
            /**
             * Planner Id
             * Format: uuid
             */
            planner_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TripFoodUpdate */
        TripFoodUpdate: {
            /** Day */
            day?: number;
            /** Name */
            name?: string;
            meal_type?: components["schemas"]["Meal"];
            /** Servings */
            servings?: number;
            /** Weight G */
            weight_g?: number;
            /** Kcal */
            kcal?: number;
        };
        /** TripGearCreate */
        TripGearCreate: {
            /**
             * Gear Item Id
             * Format: uuid
             */
            gear_item_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /**
             * Packed
             * @default false
             */
            packed: boolean;
        };
        /** TripGearRead */
        TripGearRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            gear_item: components["schemas"]["GearItemRead"];
            /** Quantity */
            quantity: number;
            /** Packed */
            packed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TripGearUpdate */
        TripGearUpdate: {
            /** Quantity */
            quantity?: number;
            /** Packed */
            packed?: boolean;
        };
        /** TripNoteCreate */
        TripNoteCreate: {
            /** Content */
            content: string;
        };
        /** TripNoteRead */
        TripNoteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Content */
            content: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TripNoteUpdate */
        TripNoteUpdate: {
            /** Content */
            content?: string;
        };
        /** TripRead */
        TripRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Area */
            area: string | null;
            trip_type: components["schemas"]["TripType"];
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Start Trailhead */
            start_trailhead: string | null;
            /** End Trailhead */
            end_trailhead: string | null;
            /** Total Distance M */
            total_distance_m: number | null;
            /** Elevation Gain M */
            elevation_gain_m: number | null;
            /** Water Carry L */
            water_carry_l: number;
            /** Map Link */
            map_link: string | null;
            /** Emergency Contact */
            emergency_contact: string | null;
            food_plan: components["schemas"]["FoodPlannerRead"] | null;
            /** Gear List */
            gear_list: components["schemas"]["TripGearRead"][];
            /** Checklist Items */
            checklist_items: components["schemas"]["ChecklistItemRead"][];
            /** Notes */
            notes: components["schemas"]["TripNoteRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Checklist Ready
             * @description True when no checklist item is still to do (done and not-applicable both count).
             */
            readonly checklist_ready: boolean;
        };
        /**
         * TripType
         * @enum {string}
         */
        TripType: "loop" | "out-and-back" | "point-to-point";
        /** TripUpdate */
        TripUpdate: {
            /** Name */
            name?: string;
            /** Description */
            description?: string | null;
            /** Area */
            area?: string | null;
            trip_type?: components["schemas"]["TripType"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Start Trailhead */
            start_trailhead?: string | null;
            /** End Trailhead */
            end_trailhead?: string | null;
            /** Total Distance M */
            total_distance_m?: number | null;
            /** Elevation Gain M */
            elevation_gain_m?: number | null;
            /** Water Carry L */
            water_carry_l?: number;
            /** Map Link */
            map_link?: string | null;
            /** Emergency Contact */
            emergency_contact?: string | null;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "metric" | "imperial";
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserPublic */
        UserPublic: {
            /** Username */
            username: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Picture */
            picture?: string | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Picture */
            picture?: string | null;
            /** Body Weight G */
            body_weight_g?: number | null;
            measurements: components["schemas"]["Unit"];
            status: components["schemas"]["UserStatus"];
            role: components["schemas"]["UserRole"];
            /** First Login */
            first_login?: string | null;
            /** Last Login */
            last_login?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "admin" | "unauthenticated";
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "blocked";
        /** UserUpdate */
        UserUpdate: {
            /** Username */
            username?: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Picture */
            picture?: string | null;
            /** Body Weight G */
            body_weight_g?: number | null;
            measurements?: components["schemas"]["Unit"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"][];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["UserStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_user_api_v1_admin_users__user_id__approve_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_user_api_v1_admin_users__user_id__suspend_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_role_api_v1_admin_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"][];
                };
            };
        };
    };
    create_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_v1_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_v1_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_api_v1_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_trip_gear_api_v1_trips__trip_id__gear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripGearCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripGearRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_trip_gear_api_v1_trips__trip_id__gear_copy_from__source_trip_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_trip_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripGearRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_trip_gear_api_v1_trips__trip_id__gear__trip_gear_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_gear_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_gear_api_v1_trips__trip_id__gear__trip_gear_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_gear_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripGearUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripGearRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_v1_trips__trip_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripNoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_trips__trip_id__notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_v1_trips__trip_id__notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripNoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripNoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_checklist_item_api_v1_trips__trip_id__checklist__item_key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_key: components["schemas"]["ChecklistItemKey"];
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_food_plan_api_v1_trips__trip_id__food_plan_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodPlannerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodPlannerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_food_item_api_v1_trips__trip_id__food_plan_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripFoodCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripFoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_food_item_api_v1_trips__trip_id__food_plan_items__food_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_food_item_api_v1_trips__trip_id__food_plan_items__food_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: string;
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripFoodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripFoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gear_items_api_v1_gear_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gear_item_api_v1_gear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GearItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gear_item_api_v1_gear__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_gear_item_api_v1_gear__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gear_item_api_v1_gear__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GearItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_gear_item_api_v1_gear__item_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
